import = ["/home/crw/.config/alacritty/themes/themes/breeze.toml"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.normal.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.normal.italic]
family = "JetBrainsMono NF"
style = "Italic"

[window]
opacity = 0.9
