[helpers]

#-------------------------------------------------------------------------------
# shell
#-------------------------------------------------------------------------------

[shell.files]
gdbinit = { target = "~/.config/gdb/gdbinit", type = "symbolic" }
gh = "~/.config/gh"
gitconfig = "~/.gitconfig"
scripts = "~/bin"
"tmux.conf" = "~/.tmux.conf"
env = "~/.env"
lazygit = "~/.config/lazygit"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[bash]
depends = ["shell"]

[bash.files]
bashrc = "~/.bashrc"

[zsh]
depends = ["shell"]

[zsh.files]
zshrc = "~/.zshrc"

[fish]
depends = ["shell"]

[fish.files]
fish = "~/.config/fish"

#-------------------------------------------------------------------------------
# terminal
#-------------------------------------------------------------------------------

[alacritty.files]
alacritty = { target = "~/.config/alacritty", type = "symbolic" }

[kitty.files]
kitty = { target = "~/.config/kitty", type = "symbolic" }

#-------------------------------------------------------------------------------
# windows manager
#-------------------------------------------------------------------------------

[hypr]
depends = ["waybar", "rofi"]

[hypr.files]
hypr = "~/.config/hypr"

[waybar.files]
waybar = "~/.config/waybar"

[rofi.files]
rofi = "~/.config/rofi"

#-------------------------------------------------------------------------------
# others
#-------------------------------------------------------------------------------

[conda.files]
condarc = "~/.condarc"

[font.files]
fontconfig = "~/.config/fontconfig"

[idea.files]
ideavimrc = "~/.ideavimrc"

[nvim.files]
nvim = { target = "~/.config/nvim", type = "symbolic" }

[zathura.files]
zathurarc = "~/.config/zathura/zathurarc"
