[helpers]

######################################################################
# shell
######################################################################

[shell.files]
gdbinit = "~/.config/gdb/gdbinit"
gh = "~/.config/gh"
gitconfig = "~/.gitconfig"
ranger = { target = "~/.config/ranger", type = "symbolic"}
joshuto = "~/.config/joshuto"
scripts = "~/bin"
"tmux.conf" = "~/.tmux.conf"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[bash]
depends = ["shell"]

[bash.files]
bashrc = "~/.bashrc"

[zsh]
depends = ["shell", "starship"]

[zsh.files]
zshrc = "~/.zshrc"

[fish]
depends = ["shell", "starship"]

[fish.files]
fish = "~/.config/fish"

######################################################################
# terminal
######################################################################

[alacritty.files]
alacritty = { target = "~/.config/alacritty", type = "symbolic" }

######################################################################
# others
######################################################################

[conda.files]
condarc = "~/.condarc"

[font.files]
fontconfig = "~/.config/fontconfig"

[idea.files]
ideavimrc = "~/.ideavimrc"

[nvim.files]
nvim = { target = "~/.config/nvim", type = "symbolic"}

[zathura.files]
zathurarc = "~/.config/zathura/zathurarc"

